### PR TITLE
Correct formatting

### PR DESCRIPTION
**Pull request by mukeshpanchal27**

### CODE REVIEW

**Comment by JulieKuehl** [comment]
Having troubles pulling this one in as there is a conflict. Will try again later.

**Comment by JulieKuehl** [comment]
I am having trouble pulling this one in. GitHub says there are conflicts but it's not letting me resolve them. I will continue to see what can be done. They are good changes!

**Comment by mukeshpanchal27** [comment]
@JulieKuehl Let me know in case of fresh PR request needed.

**Comment by JulieKuehl** [comment]
Well, that took far too long for me to respond, but thank you for your contribution! Your pull request has been merged.

**Pull request merged**
